name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Build project
        run: npm install && npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: deployment-artifact
          path: ./dist

      - name: Deploy Page
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: deployment-artifact
          token: ${{ secrets.GITHUB_TOKEN }}



